const Menu = [
    {
        id: 1,
        category: "comapny",
        name: "Perfumes, perfumed or eau de toilette?",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img1.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.'
    },
    {
        id: 2,
        category: "comapny",
        name: "Best multi-step skin care treatment",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img2.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.',
    },
    {
        id: 3,
        category: "comapny",
        name: "Best multi-step skin care treatment",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img3.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.',
    },
    {
        id: 4,
        category: "comapny",
        name: "Best multi-step skin care treatment",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img4.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.',
    },
    {
        id: 5,
        category: "Shopes",
        name: "Best multi-step skin care treatment",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img5.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.',
    },
    {
        id: 6,
        category: "Shopes",
        name: "Best multi-step skin care treatment",
        dec: 'Nourish your skin with toxin-free cosmetic products. With the offers that yo skin with toxin-free cosmetic products that you can’t refuse.',
        src: "img/blog-img6.jpg",
        dec2:' The history of perfume is about 5,000 years old and dates back to ancient Egypt and Mesopotamia. The fragrances of those times differed significantly from modern ones in that they were very concentrated and were more often intended for religious ceremonies than for cosmetic purposes. Although the same Cleopatra had her own perfume factory and left behind a recipe for a fragrance of 16 ingredients - "kifi". It is difficult to call it a perfume in the modern sense - it is rather a mixture of oils and herbs. Modern perfumes can have a maximum of 30% aromatic component, everything else - an alcoholic solution. But do not be upset. If you do not need such extravagant appearances as in the queen of Egypt, when he fragrances of her ships spread throughout the coast, then 100% concentrate is unlikely to be needed.',
        title:'About Sustainability',
        dec3: 'It would seem that everything is clear here: the higher the concentration of aromatic components - the more stable the aroma. But not everything is so simple: even if in the laboratory the aroma stays calm for a day or more, in life it is influenced by humidity and temperature, skin condition and the aroma of your body. Therefore, experts advise to apply fragrances on a clean, moisturizing body lotion. But even this does not guarantee that super-concentrated perfumes will last longer than perfumed or eau de toilette. It all depends on the volatility of the ingredients themselves.',
    },
  
]
export default Menu;